(cl:defpackage project2_phase1-srv
  (:use )
  (:export
   "GETNEXTDESTINATION"
   "<GETNEXTDESTINATION-REQUEST>"
   "GETNEXTDESTINATION-REQUEST"
   "<GETNEXTDESTINATION-RESPONSE>"
   "GETNEXTDESTINATION-RESPONSE"
  ))

