// Generated by gencpp from file turtlebot3_object_tracker/DetectionData.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_OBJECT_TRACKER_MESSAGE_DETECTIONDATA_H
#define TURTLEBOT3_OBJECT_TRACKER_MESSAGE_DETECTIONDATA_H

#include <ros/service_traits.h>


#include <turtlebot3_object_tracker/DetectionDataRequest.h>
#include <turtlebot3_object_tracker/DetectionDataResponse.h>


namespace turtlebot3_object_tracker
{

struct DetectionData
{

typedef DetectionDataRequest Request;
typedef DetectionDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectionData
} // namespace turtlebot3_object_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_object_tracker::DetectionData > {
  static const char* value()
  {
    return "60c458eab0a342a86739c835cfee1fc3";
  }

  static const char* value(const ::turtlebot3_object_tracker::DetectionData&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_object_tracker::DetectionData > {
  static const char* value()
  {
    return "turtlebot3_object_tracker/DetectionData";
  }

  static const char* value(const ::turtlebot3_object_tracker::DetectionData&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_object_tracker::DetectionDataRequest> should match
// service_traits::MD5Sum< ::turtlebot3_object_tracker::DetectionData >
template<>
struct MD5Sum< ::turtlebot3_object_tracker::DetectionDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_object_tracker::DetectionData >::value();
  }
  static const char* value(const ::turtlebot3_object_tracker::DetectionDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_object_tracker::DetectionDataRequest> should match
// service_traits::DataType< ::turtlebot3_object_tracker::DetectionData >
template<>
struct DataType< ::turtlebot3_object_tracker::DetectionDataRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_object_tracker::DetectionData >::value();
  }
  static const char* value(const ::turtlebot3_object_tracker::DetectionDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_object_tracker::DetectionDataResponse> should match
// service_traits::MD5Sum< ::turtlebot3_object_tracker::DetectionData >
template<>
struct MD5Sum< ::turtlebot3_object_tracker::DetectionDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_object_tracker::DetectionData >::value();
  }
  static const char* value(const ::turtlebot3_object_tracker::DetectionDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_object_tracker::DetectionDataResponse> should match
// service_traits::DataType< ::turtlebot3_object_tracker::DetectionData >
template<>
struct DataType< ::turtlebot3_object_tracker::DetectionDataResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_object_tracker::DetectionData >::value();
  }
  static const char* value(const ::turtlebot3_object_tracker::DetectionDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_OBJECT_TRACKER_MESSAGE_DETECTIONDATA_H
